Page, Form y Breadcrumb w/responsive
sync-ideas/project-frontend pull request #16
Opened 2023-10-25 23:35 UTC by rafaric

page done, miss navbar for complete

2023-10-30 17:05 UTC, TatianaSanchez01 requested changes
This pull request contains some necessary changes before it can be merged. Here are the specific changes that are required:

1. Missing Merge from Dev Branch:
   - It appears that the changes in the navbar are missing from the development (dev) branch. Please ensure that all the navbar updates are properly merged from the dev branch.

2. Form Width:
   - The form in the current code is not extending to the desired width. Please adjust the form's width to match the specified width requirements from the design.

3. Center Placeholder:
   - The placeholder text in the form is not centered as shown in the design.

4. Missing Hover Effect:
   - There's a missing hover effect that needs to be implemented. Ensure that the necessary rules for hover interactions are added for the affected elements.

Please make these adjustments and update the pull request accordingly. Once these changes have been made, the pull request can be reviewed and merged.

2023-11-15 20:28 UTC, rafaric commented
All adjustments and updates did.

2023-11-16 15:06 UTC, TatianaSanchez01 requested changes
There is adjustments to be made. Communicated by private message

2024-03-04 20:29 UTC, TatianaSanchez01 approved these changes

2024-03-19 22:33 UTC, merged