Pd 226 crear componente bread crumb link
sync-ideas/project-frontend pull request #20
Opened 2023-11-27 23:40 UTC by rafaric

Esta rama ya tiene todos los cambios de la rama new-professor a excepción de la eliminación de las validaciones que le había agregado y que no debían incluirse. Ese cambio está en la rama new-professor.

2023-12-02 16:12 UTC, TatianaSanchez01 requested changes
Here's are some request for changes regarding the breadcrumb component:

1. Breadcrumb Styling:
   - The current breadcrumb component deviates from the design specifications. To align with the design:
     - Remove the pointer cursor for the breadcrumb.
     - Ensure there is no decoration applied to the breadcrumb.
     - Adjust the text color to purple for the active page link, the specific tailwind color is purple-text.
     - Apply an opacity of 0.7 to the text color for links corresponding to non-active pages, you can change the tailwind configuration if needed.

This modification ensures that the breadcrumb component adheres to the design guidelines, enhancing the overall visual consistency. Thank you!

2023-12-05 01:22 UTC, rafaric commented
Changes applied. The non-active links has now a gray color, like in prototype.

2023-12-05 14:19 UTC, TatianaSanchez01 approved these changes

2023-12-05 20:19 UTC, rafaric commented
delelted volver link

2023-12-05 23:07 UTC, merged