Feat/password-recovery-view
sync-ideas/project-frontend pull request #8
Opened 2023-10-03 15:11 UTC by TatianaSanchez01

2023-10-03 23:52 UTC, BrayanGalindez requested changes
Everything looks good, but the commit title is in Spanish

2023-10-06 20:59 UTC, JM-joaquin approved these changes

2023-10-12 16:35 UTC, BrayanGalindez requested changes
font not according to the design

2023-10-20 00:27 UTC, BrayanGalindez approved these changes
Everything looks good

2023-10-20 21:08 UTC, merged