Feat/view message
sync-ideas/project-frontend pull request #9
Opened 2023-10-04 17:40 UTC by JM-joaquin

@BrayanGalindez @TatianaSanchez01

2023-10-12 16:40 UTC, BrayanGalindez requested changes
the font does not match the layout and the view is not a responsive layout

2023-10-20 00:20 UTC, BrayanGalindez commented
On a 1280x720 screen it is not according to the design

2023-10-30 16:55 UTC, TatianaSanchez01 approved these changes

2023-11-11 20:51 UTC, BrayanGalindez approved these changes

2023-11-16 01:40 UTC, merged